modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/marcus8448/GamemodeOverhaul/issues/"
#logoFile=""

[[mods]]
    modId="gamemodeoverhaul"
    version="1.14.4-1.4.2.2"
    updateJSONURL="https://marcus8448.github.io/GamemodeOverhaul/version.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/gamemodeoverhaul"
    displayName="GamemodeOverhaul"
    authors="marcus8448"
    description='''
Changes the Vanilla '/gamemode' command to allow numbers and letters again!

Adds a new command '/gm' if you don't want to write "gamemode"
Also adds even shorter gamemode changing commands ex. "/gmc" (creative)

You may also use '/difficulty [id]' again!
Plus much, much more!

See the CurseForge page for more details: https://www.curseforge.com/minecraft/mc-mods/gamemodeoverhaul
'''

[[dependencies.gamemodeoverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamemodeoverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"