modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/marcus8448/GamemodeOverhaul/issues/"
#logoFile=""

[[mods]]
    modId="gamemodeoverhaul"
    version="1.14.2-1.4.0.0"
    updateJSONURL="https://marcus8448.github.io/GamemodeOverhaul/version.json"
    displayURL="https://marcus8448.github.io/GamemodeOverhaul"
    displayName="GamemodeOverhaul"
    authors="marcus8448"
    description='''
Changes the Vanilla '/gamemode' command to allow numbers and letters again!

Adds a new command '/gm' if you don't want to write "gamemode"
Also adds even shorter gamemode changing commands ex. "/gmc" (creative)

You may also use '/difficulty [id]' again!
Plus much, much more!
'''

[[dependencies.gamemodeoverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamemodeoverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"