modLoader="javafml"
loaderVersion="[${min_fml},)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${mod_id}.png"
credits=""
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[${min_neoforge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${min_minecraft},)"
    ordering="NONE"
    side="BOTH"
