name: Commit

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            common/.gradle
            fabric/.gradle
            neoforge/.gradle
            neoforge/build/jars
            neoforge/build/neoForge
            neoforge/build/neoForm
            neoforge/build/tmp/neoFormRecompile
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/gradle-wrapper.properties', 'settings.gradle.kts', '**/build.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Initialize build environment
        run: ./gradlew

      - name: Check license headers
        run: ./gradlew spotlessCheck

      - name: Build
        if: ${{ !cancelled() }}
        id: build
        run: ./gradlew assemble -x spotlessCheck
